### ISSUE TITLE
Overfull \hbox when setting table width

### ISSUE THREAD

**Issue by T-Tonic** [mmerino25/tblr-extras#3]
The MWE below gives a overfull \hbox warning. The warning goes away if  `width = 0.85\textwidth` is removed.

```
\documentclass{article}

\usepackage[tableposition=top,width=\textwidth]{caption}
\usepackage{tabularray}
\usepackage{tblr-extras}
\UseTblrLibrary{caption}

\begin{document}

\begin{table}[!htb]
    \centering
    \begin{talltblr}[
            caption = {Test},
        ]{
            colspec={|X|X|X|},
            width = 0.85\textwidth,
        }
        \hline
        A & B & C \\
        \hline
        D & E & F \\
        \hline
    \end{talltblr}
\end{table}

\end{document}
```

**Comment by mmerino25** [comment]
This is kinda expected? You are making a fullwidth caption with a table that only spans 0.85 of the textwidth. 
If you remove the width of the caption there is no overfull hbox anymore.

**Comment by T-Tonic** [comment]
Ah, sorry. This is because it is the internal caption of the talltblr and not the caption of the float?

**Comment by mmerino25** [comment]
Yes. The caption library is intended to replace the implementation of the internal captions of tall and long tblr environments. If you want a float caption, use `\caption` instead and disable the talltblr caption (check documentation of tabularray and tblr-extras).
